#! /usr/bin/perl

# usage: update-peers [file]
# Defaults to use $PWD/bgp-peers.csv

use strict;
use File::Copy;
use LWP::Simple;                # From CPAN
use JSON qw( decode_json );     # From CPAN

my $tmpdir="/tmp";
my $basedir=".";
my $input;
my $force;

if ($ARGV[0] eq "-f") {
	$input= $ARGV[1] || "$ENV{PWD}/bgp-peers.csv";
        $force=1;
} else {
        $input= $ARGV[0] || "$ENV{PWD}/bgp-peers.csv";
}

my %asn_counter;

sub readfile {
        return `cat $_[0]`;
}


sub output_peer {
	my ($out, $asn, $template, $desc, $ip, $filter, $prefixlimit, $localpref, $passive ) = @_;
	if ($filter eq "NONE") { $filter = ""; }
	my $version;
	if ($ip =~ /:/) { $version = "6" } else {$version= "4" } 
	my $id = substr($template,0,1).$version."_".$asn.sprintf("_%02d",$asn_counter{$asn});
	my $asset = $filter;
	$filter =~ tr/-/_/;
	print $out "protocol bgp $id from $template {\n".
		   "    description \"$desc\";\n".
		   "    neighbor $ip as $asn;\n";
	if ($filter ne "") 	{ print $out "    #FILTERSET;$asn;$asset;$template\n"; }
	if ($filter ne "") 	{ print $out "    import filter ".$filter."_".$version.";\n"; }
	if ($prefixlimit ne "") { print $out "    import limit $prefixlimit action block;\n"; }
	if ($localpref ne "") 	{ print $out "    preference $localpref;\n"; }
	if ($passive !~ /\s*/) 	{ print $out "    passive on;\n"; }
	print $out "}\n\n";
}

open (my $fh, "<:encoding(UTF-8)", $input) or die "$!\n";
open (my $out4, ">", "$tmpdir/peers-v4.tmp") or die "$!\n";
open (my $out6, ">", "$tmpdir/peers-v6.tmp") or die "$!\n";

print $out4 "# UPDATED AUTOMATICALLY DO NOT EDIT!\n# Last updated: ".localtime."\n# Source: $input\n\n";
print $out6 "# UPDATED AUTOMATICALLY DO NOT EDIT!\n# Last updated: ".localtime."\n# Source: $input\n\n";

my $ix_id;
my $ix_desc;

my $header=<$fh>;
while ( ! eof ($fh) ) {
	my $line = <$fh>;
	next if ($line =~ /^\s*#/);
	chomp $line;
	my ($type, $desc, $peeringdb, $asn, $template, $ipv4, $ipv6, 
	$filterv4, $filterv6,$localpref,$prefv4,$prefv6,$passive) = split (";",$line);
	if ($type eq "IXP") {
		$ix_id = $peeringdb;
		$ix_desc = $desc;
		next;
	} elsif ( $type eq "PNI" ) {
		$ix_id = "";
		$ix_desc = "";
		next;
	}
	
	my $netfile = "$basedir/data/net/$peeringdb";
	if ($peeringdb ne "") {
        if ($force==1) {
			print "Downloading new copy of $netfile\n";
			getstore ("https://www.peeringdb.com/api/net/$peeringdb",$netfile);
	}
	if ( -s "$netfile" ) {
                my @stat=stat("$netfile");
                if (time()-$stat[9] > 43200) { 
			print "Downloading new copy of $netfile. Age: ".(time()-$stat[9])."\n";
			getstore ("https://www.peeringdb.com/api/net/$peeringdb",$netfile);
		}
	}
	}
	if ($ipv4.$ipv6 eq "" && ( -s "$netfile")) {
		my $decoded_net = decode_json( readfile("$basedir/data/net/$peeringdb") );
		if ($template eq "") { 
			if ($decoded_net->{'data'}->[0]->{'info_type'} eq "Route Server") {
				$template = "ROUTESERVER"
			} else {
				$template = "PEERING"
			}
		}
		if ($filterv4 eq "") { $filterv4=$decoded_net->{'data'}->[0]->{'irr_as_set'} }; 
		if ($filterv6 eq "") { $filterv6=$decoded_net->{'data'}->[0]->{'irr_as_set'} }; 
		if ($prefv4 eq "") { $prefv4=$decoded_net->{'data'}->[0]->{'info_prefixes4'} }; 
		if ($prefv6 eq "") { $prefv6=$decoded_net->{'data'}->[0]->{'info_prefixes6'} }; 
		my $mdesc = $desc . " at $ix_desc"; 
		my $sess = 1;
		foreach my $elem ( @{$decoded_net->{'data'}->[0]->{'netixlan_set'}} ) {
			if ($sess > 1) { $mdesc = $desc . " $sess at $ix_desc" }; 
			next if ($elem->{'ix_id'} ne $ix_id);
			$asn_counter{$asn}++;
			$ipv4 = $elem->{'ipaddr4'}; $ipv6 = $elem->{'ipaddr6'}; $asn = $elem->{'asn'};
			if ($ipv4 ne "") { output_peer($out4, $asn, $template, $mdesc, $ipv4, $filterv4, $prefv4, $localpref, $passive); }
			if ($ipv6 ne "") { output_peer($out6, $asn, $template, $mdesc, $ipv6, $filterv6, $prefv6, $localpref, $passive); }
			$sess++;
		}
	} else {
		$asn_counter{$asn}++;
		if ($ipv4 ne "") { output_peer($out4, $asn, $template, $desc, $ipv4, $filterv4, $prefv4, $localpref, $passive); }
		if ($ipv6 ne "") { output_peer($out6, $asn, $template, $desc, $ipv6, $filterv6, $prefv6, $localpref, $passive); }
	}	
}

close $fh;
close $out4;
close $out6;

move ("$tmpdir/peers-v4.tmp","$basedir/includes/peers-v4");
move ("$tmpdir/peers-v6.tmp","$basedir/includes/peers-v6");

